### ISSUE TITLE
PHP 5.3 support

### ISSUE THREAD

**Issue by grogy** [JakubOnderka/PHP-Var-Dump-Check#11]
Hi,

why are tests execute with version 5.3.3? In composer.json is required PHP 5.3.2.

**Comment by grogy** [comment]
@JakubOnderka ping up.

**Comment by JakubOnderka** [comment]
Because Travis don't support version lower than 5.3.3 (see https://github.com/travis-ci/travis-cookbooks/blob/master/ci_environment/php/attributes/default.rb). So I dropped support for 5.3.2, because I don't know, if work in that version.
