### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by malios** [JakubOnderka/PHP-Var-Dump-Check#25]
Last version of the package is v0.2 which is released on Mar 13, 2015. The README states that there are options such as --symfony, --laravel, --doctrine but in the latest release these options are not available. Do you plan to release a new version with the latest changes in the master branch?

**Comment by grogy** [comment]
Ping up.

I use current master branch in Symfony+Nette project and all looks OK. From my view is possible create new version.

**Comment by gianiaz** [comment]
./vendor/bin/var-dump-check --symfony --exclude app --exclude vendor .
Invalid option --symfony

Options:
    --tracy      Enable support for Tracy (Debugger::dump)
    --zend       Enable support for Zend (Zend_Debug::dump and \Zend\Debug\Debug::dump)
    --ladybug    Enable support for Ladybug (ladybug_dump, ladybug_dump_die, ld, ldd)
    --extensions Check only files with selected extensions separated by comma
                 (default: php, php3, php4, php5, phtml)
    --exclude    Exclude directory. If you want exclude multiple directory, use
                 multiple exclude parameters.
    --no-colors  Disable colors in console output.
    -h, --help   Print this help.

**Comment by wodka** [comment]
@JakubOnderka new release?

**Comment by TomAdam** [comment]
@JakubOnderka Is there any way we can help to get this release out?

**Comment by cwcrawley** [comment]
@JakubOnderka Any chance you can release this new version with Laravel Support?

**Comment by JakubOnderka** [comment]
Hi all, I just released new version and sorry that it takes a long time. Enjoy new release!
